name = "mail-forwarder"
main = "src/index.js"
compatibility_date = "2025-11-16"  # 更新为当前日期

[[kv_namespaces]]
binding = "KV_CONFIG"
id = "68b2cffb3ec0497f905cec67af3160fc" # 你的实际 KV_CONFIG ID

[[kv_namespaces]]
binding = "KV_LOG"
id = "7ce6f281bd524aebaff2cf801f4a2cc8" # 你的实际 KV_LOG ID

[vars]
CONFIG_URL = "https://raw.githubusercontent.com/你的用户名/mail-forwarder/main/config.json"
DEFAULT_EMAIL = "mail@mydomin.com"
